name: flutter_utils
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  dio: ^5.8.0+1
  dio_cache_interceptor: ^4.0.3
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  fpdart: ^1.1.1
  go_router: ^15.1.2
  hive_ce_flutter: ^2.3.1
  http_cache_hive_store: ^5.0.1
  internet_connection_checker_plus: ^2.7.2
  path_provider: ^2.1.5
  pretty_dio_logger: ^1.4.0
  synchronized: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
