// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcx9xvmUwRrmXVQvRp-griW-RwcmXARDM',
    appId: '1:501747332072:web:0718aa20c63ea1cc1aaa5d',
    messagingSenderId: '501747332072',
    projectId: 'flutter-utils-92a2e',
    authDomain: 'flutter-utils-92a2e.firebaseapp.com',
    storageBucket: 'flutter-utils-92a2e.firebasestorage.app',
    measurementId: 'G-Z122ET8KQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCflXJpTM1TQ1fqSnxZtKF953_qH6utWYg',
    appId: '1:501747332072:android:084474971c6c57731aaa5d',
    messagingSenderId: '501747332072',
    projectId: 'flutter-utils-92a2e',
    storageBucket: 'flutter-utils-92a2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvGb1noFpO56haxirVp2K5sEMbIF_biJ4',
    appId: '1:501747332072:ios:506733082254134c1aaa5d',
    messagingSenderId: '501747332072',
    projectId: 'flutter-utils-92a2e',
    storageBucket: 'flutter-utils-92a2e.firebasestorage.app',
    iosBundleId: 'com.example.flutterUtils',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvGb1noFpO56haxirVp2K5sEMbIF_biJ4',
    appId: '1:501747332072:ios:506733082254134c1aaa5d',
    messagingSenderId: '501747332072',
    projectId: 'flutter-utils-92a2e',
    storageBucket: 'flutter-utils-92a2e.firebasestorage.app',
    iosBundleId: 'com.example.flutterUtils',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcx9xvmUwRrmXVQvRp-griW-RwcmXARDM',
    appId: '1:501747332072:web:c0b68cbbe0df4d131aaa5d',
    messagingSenderId: '501747332072',
    projectId: 'flutter-utils-92a2e',
    authDomain: 'flutter-utils-92a2e.firebaseapp.com',
    storageBucket: 'flutter-utils-92a2e.firebasestorage.app',
    measurementId: 'G-TP8Y0M3HS2',
  );
}
